sudo: true
language: c
services: docker
addons:
  mariadb: '10.3'
  apt:
  packages:
    - mariadb-server
  hosts:
    - mariadb.example.com
#  homebrew:
#    packages:
#      - openssl
#      - libiodbc
#      - mariadb

before_install:
  #- chmod +x .travis/script.sh
  #- chmod +x .travis/osx.sh
  #- chmod +x .travis/gen-ssl.sh
  #- chmod +x .travis/build/build.sh
  #- chmod +x .travis/build/docker-entrypoint.sh
  - chmod +x .travis/s390x.sh
  - chmod 777 .travis/build/
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export SSLCERT=$PROJ_PATH/tmp

matrix:
  include:
    - os: linux
      arch: s390x
      dist: bionic
     
script:
   .travis/s390x.sh
