sudo: true
language: c
services: docker
addons:
  hosts:
    - mariadb.example.com
    
addons:
  apt:
    update: true
    
addons:
  mariadb: '10.3'
  
before_install:
  - chmod +x .travis/s390x.sh
  - chmod 777 .travis/build/
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export SSLCERT=$PROJ_PATH/tmp

matrix:
  include:
    - os: linux
      arch: s390x
      dist: focal
#      language: GENERIC
      
script:
  - if [[ "$DB" == build* ]] ; then .travis/build/build.sh; fi
  - if [[ "$DB" == build* ]] ; then docker build -t build:10.6 --label build .travis/build/; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_ARCH" != "s390x" ] ; then .travis/script.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then .travis/osx.sh; fi
  - DEBIAN_FRONTEND=noninteractive sudo apt-get update
  - sudo service mysql stop
  - sudo rm -rf /etc/mysql /var/lib/mysql /var/log/mysql
  - sudo apt purge -y mysql-server mysql-client mysql-common 
  - sudo apt autoremove -y
  - travis_wait 30 DEBIAN_FRONTEND=noninteractive sudo apt-get install -y mariadb-server unixodbc-dev git cmake gcc libssl-dev tar curl libcurl4-openssl-dev libkrb5-dev

#  - if [ "$TRAVIS_ARCH" = "s390x" ]; then .travis/s390x.sh; fi
