sudo: true
language: c
services: docker
addons:
  hosts:
    - mariadb.example.com

matrix:
  include:
    - os: linux
      if: type = push AND branch = test_travis
      install: chmod +x .travis/s390x.sh
      arch: s390x
      dist: focal
      addons:
        mariadb: '10.3'

script:
  - if [[ "$DB" == build* ]] ; then .travis/build/build.sh; fi
  - if [[ "$DB" == build* ]] ; then docker build -t build:10.6 --label build .travis/build/; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_ARCH" != "s390x" ]; then .travis/script.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then .travis/osx.sh; fi
  - if [ "$TRAVIS_ARCH" = "s390x" ]; then .travis/s390x.sh; fi
  
  
