sudo: true
language: c
services: docker
addons:
  hosts:
    - mariadb.example.com

before_install:
  - chmod 777 .travis/s390x.sh
  - export PROJ_PATH=`pwd`
  - export ENTRYPOINT=$PROJ_PATH/.travis/sql
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export SSLCERT=$PROJ_PATH/tmp

matrix:
  allow_failures:
    - os: linux
      arch: s390x
      dist: focal    
      
script:      
  .travis/s390x.sh; 
